// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbgbGgb0OesSCgZD9lSBTXQAKmaHTS4yE',
    appId: '1:715791241789:web:81b4eb242560c7d7fd9054',
    messagingSenderId: '715791241789',
    projectId: 'lokka-069',
    authDomain: 'lokka-069.firebaseapp.com',
    storageBucket: 'lokka-069.firebasestorage.app',
    measurementId: 'G-F9921BNDFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8krLsyuwGJM1yugfb56K6rkiPZXdQkS4',
    appId: '1:715791241789:android:11e90b85d6f9980ffd9054',
    messagingSenderId: '715791241789',
    projectId: 'lokka-069',
    storageBucket: 'lokka-069.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSJKtTMX_ehkx7mV-UvgsK31VgCElftkQ',
    appId: '1:715791241789:ios:4c34d5ff8dae22b6fd9054',
    messagingSenderId: '715791241789',
    projectId: 'lokka-069',
    storageBucket: 'lokka-069.firebasestorage.app',
    iosClientId: '715791241789-dbgpr1v3bfq2o5p2ocvolnfnedj2jqh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.lokka',
  );

}